### ISSUE TITLE
Bootstrap 4 -> tailwind support?

### ISSUE THREAD

**Issue by austinkregel** [awssat/tailwindo#10]
What would it take to get to support bootstrap 4?

**Comment by abdumu** [comment]
Actually the converter was written for Bootstrap 4, but the early versions, not the final.

**Comment by austinkregel** [comment]
Oh cool :D I didn't know that xD

**Comment by autoferrit** [comment]
Was this ever updated to the current released version of BS4?

**Comment by Herz3h** [comment]
It would be nice to specify somewhere what bootstrap version is supported with this tool. Currently using BS 3.4.1, is it compatible ?

**Comment by abdumu** [comment]
@Herz3h it's there, latest version will print a message 'from bootstrap 4.? to tailwind 1.?'
