### ISSUE TITLE
Nothing seems to work, no conversion.

### ISSUE THREAD

**Issue by lstables** [awssat/tailwindo#12]
I've done commands like

`tailwindo /resources/views/auth/login.blade.php` & `tailwindo /resources/views/ --recursive=true` but nothing changes, stays as bootstrap, any ideas?

**Comment by austinkregel** [comment]
Try removing the `/` from the beginning of resources. If it's there, tailwindo should be trying to pull files from the root of your file system. Removing it will tell tailwindo to recurse relative to the directory you're in.

**Comment by lstables** [comment]
Thanks, i will try that.
