### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by HDVinnie** [awssat/tailwindo#17]
### Issue Type
- [x] Question

### End User Info
-- Laravel Version: 5.7.24

-- PHP Version: 7.2.14

-- Database Driver & Version: MySQL 5.7.25

-- Web Server Driver & Version: nginx/1.15.6

-- OS Driver and Version: Ubuntu 18.04.1

I have installed the package successfully but when run the command I get a error.Any ideas here?

```
_> /var/www/html# tailwindo resources/views/Staff
tailwindo: command not found
```

**Comment by abdumu** [comment]
check #9

**Comment by HDVinnie** [comment]
I did but I'm not getting it. I tried

```
_> /var/www/html# tailwindo /var/www/html/resources/views/Staff
tailwindo: command not found
```

Or am I misunderstanding `added the install directory to PATH`. Its little bland.

**Comment by abdumu** [comment]
use the full path 
```~/.composer/vendor/awssat/tailwindo/tailwindo ....```

**Comment by HDVinnie** [comment]
Thanks

**Comment by rationalthinker1** [comment]
I ran `composer require awssat/tailwindo` and I could find it under `vendor/bin` inside my project.
