### ISSUE TITLE
sr-only accidentally removed

### ISSUE THREAD

**Issue by brennanangel** [awssat/tailwindo#26]
Tailwindo removed `.sr-only` on a div. 

This is a common bootstrap/tailwindcss utility: https://tailwindcss.com/docs/screen-readers/

Guessing that's happening because this line is commented out: https://github.com/awssat/tailwindo/blob/7a79192e709c61457f7e9a59e14e98a49a9b816b/src/Framework/BootstrapFramework.php#L152

**Comment by abdumu** [comment]
Yes! 
Can you open a PR for this?
