### ISSUE TITLE
Question: Can I convert bootstrap.css to tailwind CSS using @apply?

### ISSUE THREAD

**Issue by woutersamaey** [awssat/tailwindo#38]
I'm looking to convert Bootstrap 3 to Tailwind CSS so that all Bootstrap 3 classes continue to work, but use @apply to map to Tailwind classses.

This tool appears to be working on HTML, but can it work on CSS without the need for a HTML file?

If not, guess I need an HTML file that uses ALL of Bootstrap 3 as an input source...

**Comment by abdumu** [comment]
https://awssat.com/opensource/tailwindo/2_quick-start.html#extract-changes-to-a-single-css-file
