### ISSUE TITLE
Installation questions

### ISSUE THREAD

**Issue by kb-coder** [awssat/tailwindo#39]
I'm trying to install tailwindo, but it requires PHP and Composer. Docs don't say what version of PHP or Composer are required. When I run the installation command I'm getting a message that:
` Package awssat/tailwindo has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version`. Can you provide more information on how to configure PHP / Composer to work with this?

**Comment by abdumu** [comment]
What version of PHP do you have? 
The requirement is ^7.2.0

**Comment by shoemoney** [comment]
says same for me.  


composer global require awssat/tailwindo

Changed current directory to /Users/shoemoney/.composer


  [InvalidArgumentException]
  Package awssat/tailwindo has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

❯ composer -V
Composer version 2.0.9 2021-01-27 16:09:27
❯ php -v
PHP 8.0.2 (cli) (built: Feb  4 2021 18:57:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Xdebug v3.0.2, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies

**Comment by shoemoney** [comment]
I bought this boot strap theme only cause this exists.   Looks very cool!
