### ISSUE TITLE
BoostrapFramework.php missing bg- on line 538

### ISSUE THREAD

**Issue by allcreatures** [awssat/tailwindo#40]
Apologies, I would have done a PR but editor reformats your page add a slew of additional diffs. Line 538 is:

            'success'   => 'bg-green-500 text-white hover:green-600',

But should be 

            'success'   => 'bg-green-500 text-white hover:bg-green-600',

**Comment by abdumu** [comment]
You could’ve done it online through github website.

try.

**Comment by allcreatures** [comment]
Aha, of course. Completely forgot about doing it directly in GitHub. PR created.
