### ISSUE TITLE
Wont install on latest php/composer

### ISSUE THREAD

**Issue by shoemoney** [awssat/tailwindo#43]
omposer global require awssat/tailwindo

Changed current directory to /Users/shoemoney/.composer

[InvalidArgumentException]
Package awssat/tailwindo has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] []...

❯ composer -V
Composer version 2.0.9 2021-01-27 16:09:27
❯ php -v
PHP 8.0.2 (cli) (built: Feb 4 2021 18:57:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
with Xdebug v3.0.2, Copyright (c) 2002-2021, by Derick Rethans
with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies

**Comment by shoemoney** [comment]
fixed it by changing require to 

 "require": {
         "php" :"^7.2|^8.0",
         "symfony/console": "^5.2"
     },

I have never done a PR and am under a time crunch maybe i will be able to if nobody can update.    Hope this helps others until

Great piece of software!!

**Comment by abdumu** [comment]
Try now
