### ISSUE TITLE
Recursive search and replace, custom extensions, and a way to replace files

### ISSUE THREAD

**Issue by austinkregel** [awssat/tailwindo#5]
Greetings!

I have been messing around with this codebase a little bit today and have some custom changes I put togeterh. My changes include the following:

  - Add recursive flag option to allow the scan to go more than one directory deep. 
  - Add exts option to allow for custom file extensions (adding this will allow for Vue file support)
  - Add an option to replace the files, probably would be used in conjunction with `--recursive=true` just to make change files much more easy.

My big question is if you would like these changes, and if you would, would you prefer one PR or multiple PRs for these changes.

I merged all my changes onto my master branch, and I tried to keep all other branches as clean as possible in case only a one or two of the changes were desired.

**Comment by abdumu** [comment]
Thanks, I like these ideas. 
Separating the PRs is better, so it will be easier to revert in case of any problem.
Also it will be great if you change the README file to include an explanation of these options.

@austinkregel 👏🏼

**Comment by austinkregel** [comment]
Can do :smile:
