### ISSUE TITLE
React bootstrap support.

### ISSUE THREAD

**Issue by vikasg603** [awssat/tailwindo#51]
Is there any way to convert react-bootstrap, which is using only bootstrap classes, to tailwindcss?

**Comment by abdumu** [comment]
Did you try it and failed?

**Comment by vikasg603** [comment]
> Did you try it and failed?
> […](#)
> On 24 Jun 2021, 12:28 PM +0300, vikas gupta ***@***.***>, wrote: Is there any way to convert react-bootstrap, which is using only bootstrap classes, to tailwindcss? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

No, I did not try yet, but as there was no mention of React, I assumed there was no support.

**Comment by abdumu** [comment]
https://github.com/awssat/tailwindo/pull/37

**Comment by vikasg603** [comment]
Thanks, @abdumu, for the reference.
I hope that @awssat will update the documentation, which tells that this library also support jsx.
